# coding: utf-8


def pick_blurb(row, col):
    # This file returns the specific ds blurb needed for the results page

    blurbs = [  #'Data Businessperson', 'Data Creative', 'Data Researcher', 'Data Engineer']
        [  # Programming
            """You're a relatively rare breed -- a Data Businessperson who specializes in software development. How did you get here? Perhaps you started writing code, than realized your passion for entrepeneurship or consulting. You probably realized earlier than others around you the value of the data in your organization's relational databases, and the value of systems that extract and organize that data. Over the years, you've seen fads come and go, and aren't convinced this "Data Science" label is going to stick. Focus on your strengths -- leading teams that build systems and products that allow deep insights to be extracted from data. But you might spend some effort to broaden your knowledge of data visualization and statistics, so you can sell your work in an even more compelling way.""",
            """Most Data Creatives can write programs, but that's your core skill. You live and breathe web services, databases, and Javascript.  You've embraced the culture of Open Source, and may have contributed code (or data) yourself. But Data Science appeals to you, in its diversity of approaches and its enthusiastic embrace of exploration and problem-solving with data. Focus on your strengths -- building complete systems that integrate data, analytic components, and compelling visualizations. To broaden your appeal, and differentiate yourself from the software development masses, work with statistics and machine learning tools and techniques.""",
            """Being a Data Researcher with core skills in Programming is an unusual combination and also a valuable one. You know that the key to solving problems efficiently and repeatably is to write code, and that an insight from data is most useful if it can be used as part of a software system. One-off solutions are for academics. You think about problems differently from Data Engineers, with a deeper level of domain expertise and a more scientific approach to problem solving. To focus on your strengths, make sure you're accomplished in the full technology stack, from databases to web-based front-end development. But by working on systems that integrate massive datasets and analytical components, and thinking creatively about how to solve problems with a statistical flavor, you'll have the unique combination of breadth and depth that gets results.""",
            """Most Data Engineers can write code, but that's your core skill. You live and breathe databases and software development. You've embraced the culture of Open Source, and so the open, eclectic culture of Data Science appeals to you. You'd probably like to do more with Big Data and with the exploration of unstructured data sets. So focus on your strengths -- building complete systems that integrate massive datasets and analytical components. As an engineer pushing for smarter uses of data, you'll be a hero to the business side of things. To broaden your skills, consider working with some of the new Business Intelligence and Predictive Analytics as a Service tools, and learning best practices for data visualization and interpretation.""",
        ],
        [  # Stats,
            """As a Data Businessperson who specializes in Statistics, you might be a quantitative marketer who uses survey research, data analysis, and visualization to help organizations better sell their products or services. Compared with other Data Scientists, you're probably more focused on the bottom line and the customer, and less focused on technology trends or the new buzzwords. But you're an important driving force behind organizational culture changes, pushing for data-driven decision making and thoughtful action. You're more likely than others in this field to be female, to have an MBA, to have managed employees or worked for yourself. Focus on your strengths -- communication about data and the value of data, asking the right questions, and being honest with the results. But it may be valuable to develop your programming skills and to learn more about the broader world of analytics, so that you can dive more deeply into problems on your own.""",
            """As a Data Creative with core skills in Statistics, you can talk the talk as well as walk the walk. It's not enough to analyze the data with rigor, you have to be able to communicate the results, whether in person or via compelling visualizations. You may have some graduate work in a scientific field, a compelling background for working with organizational data. But your real skills were in getting stuff done using any tool that's handy, whether it's sucking data from web services, building a complex regression model, or quickly learning a new technique or new problem domain. Focus on those strengths -- modeling data from any source, thinking scientifically about problems, and effectively conveying to others what you find. But think about ways to integrate your results into processes or systems more effectively  -- an insight that doesn't help others make decisions isn't very valuable.""",
            """Many Data Researchers specialize in Statistics skills, and you're no exception. If you don't think of yourself as a Data Scientist, it's probably because you feel like the term is just a rebranding of "Applied Statistician." Regardless, you have the valuable skill to think scientifically about a broad range of problems, and to apply the tools of statistics and the scientific method to data of all sorts. You can solve complex problems, communicate the results effectively, and build complex models of the world an organization finds itself in. Focus on your strengths -- cutting edge analytical tools, especially those that work on very large or unstructured data, and your statistically sophisticated way of thinking about problems. But your effectiveness could be even stronger with more breadth, be it in machine learning approaches, or programming skills, or experience in business environments.""",
            """As the rarest type of Data Engineer, with core skills in Statistics, you know that it's not enough to analyze the data, or build a toy model; you have to be able to put your insights into practice. Your educational background -- likely graduate work in a scientific field -- gives you the tools that you need to speak with authority about a problem, while your grounded experience gives you the broad set of tools of a Data Scientist, even if you may not care for the term. So focus on your core strengths of data analysis, visualization, and communication, while continuing to better understand your problem domain and how to better answer the most important questions. It never hurts to develop better programming or business skills either -- all the better for getting things done the right way.""",
        ],
        [  # Math/OR
            """As a Data Businessperson with Math, Algorithms or Operations Research talents, you may be coming at Data Science from a different perspective than a lot of your peers -- you probably haven't embraced the new buzzwords. But you've as committed as anyone to the value of rigorous analysis around organizational data, and to the importance of making optimal use of that data. You're more likely to be female than many other types of Data Scientists, although it's definitely a male-dominated community. Focus on your strengths -- problem solving, thinking outside the box, working in teams to get amazing results. But it's worth keeping current in other areas -- consider learning more about Big Data technology, or picking up some new statistical techniques. """,
            """Most Data Creatives have broad skillsets, but you specialized in the hard stuff -- Math or Algorithms or Operations Research. But perhaps you've pivoted away from an academic focus to solve organizational problems. As a Jack of All Trades, you may be focused on the value of Open Data, or the insights derivable from integrating data from multiple sources. But your background keeps you practical and rigorous, and that's a strength. Focus on your strengths -- problem solving and thinking about and optimizing complex systems. But keep your programming skills sharp. If you can build and demonstrate a complete system, from database to visualization, your sophisticated approach to the data becomes that much more unique and valuable.""",
            """As a Data Researcher who specializes in Machine Learning or Big Data, you're almost the quintessential Data Scientist! In fact, of all the types of Data Scientist, you're the most likely to embrace the label. Your years of education, likely in Computer Science, give you an unparalleled ability to work creatively with the newest technologies and the biggest data. You can pull insights from data sets from Hadoop to Twitter and back again. Your weakness is probably on the business side, and you should probably develop both domain expertise and the "soft skills" of understanding business problems to maximize your value. But focus on your strengths -- working on the cutting-edge of machine learning and Big Data.""",
            """You have a more quantitative background than most Data Engineers, with likely graduate work in Math or Computer Science or Operations Research. You may not consider yourself a Data Scientist, but you're as committed as anyone to the value of rigorous analysis around organizational data, and to the importance of making optimal use of that data. You are focused on building products that put your hard-won insights into use, making a real difference. To focus on your strengths, try learning more about different approaches to applying numerical tools to business problems, so you can work on a broader range of tasks. But keep your development and business skills broad enough that you can at least prototype and make the case for a full system on your own. """,
        ],
        [  # business
            """Like many business men and women, your primary skill set is Business -- starting business initiatives, getting projects done, managing people, and constructing Powerpoints while never taking your eyes off of the bottom line. But, you don’t think like most MBAs. Your background, perhaps in Engineering, gives you an edge when building Data Science products. You've worked with data on a daily basis, possibly for several decades. But you're probably skeptical of the Data Scientist label. You prefer "Leader." Focus on your strengths -- telling stories with data, managing technical teams, building data-driven cultures, starting data businesses. But don't neglect your technical and data-related skills -- what sets you apart is your ability to work with and understand data yourself, not just manage others.""",
            """Your top skills may be managing people and projects, but you identify as a Jack of All Trades, Hacker, or Artist. Perhaps you're the young turk in your organization, pulling creative data sources into decision-making, using your programming skills to subvert the usual channels. You may not call yourself a Data Scientist, but you've embraced the eclecticism and the new culture of data. If you haven't already, you may be thinking of starting a business or entering into consulting. That's a good idea, but focus on your strengths -- getting things done, finding creative solutions to problems, and working with smart people. If you want to broaden your skills, there are enormous opportunities to learn more about Big Data, Machine Learning, and Statistics, and to bring those skills into your daily work.""",
            """A Data Researcher with core skills in Business? Did you sell out? No, you just realized that your years in academia made you extraordinarily qualified outside the Ivory Tower and making a bit more money is never a bad thing. You can solve complex problems, communicate complex results clearly, and build sophisticated models of the world in which an organization finds itself. Bringing a data-driven way of thinking to sclerotic organizations is a skill, a skill that you have,  and you understand its worth. So focus on your strengths -- thinking creatively about data and systems, and using rigorous methods to solve business problems. And broaden your skill set by keeping familiar with the full set of data management and analysis tools available. You never know when you'll be asked to dive into a totally new type of problem.""",
            """You may view yourself as a Data Engineer, but you now spend as much time worrying about people and budgets as you do about database design or systems integration. You're doubtless good at your job -- you probably have graduate work in engineering or business, or both. You seriously understand the effort required to build a data system for an enterprise and, with your technical background, you also understand the incredible opportunity afforded by big data and predictive analytics (which is why you're here). So focus on your strengths -- thinking through complex design problems, weighing pros and cons, and leading technical people. But keep up-to-date on the statistical and machine learning stuff -- you want to be able to integrate valuable new tools as soon as they become available.""",
        ],
        [  # ML/Big Data
            """You're on the cutting edge of Data Businesspeople, diving into Big Data and its implications for organizations. You may have started a data-centric business, turning Terabytes into dollars and using the skills you learned in school as well as the practical expertise you've developed in the workplace. Compared with other Data Businesspeople, you're more likely to have embraced the Data Scientist label. Focus on your strengths -- working with Big Data and building analytical systems that deliver amazing value--but don't get lost in the code -- you need to be able to talk both business and math.""",
            """As a Data Creative with Machine Learning and Big Data skills, you are the ultimate hacker. You understand the culture of Open Source, and may have contributed code (or data) yourself. You can pull data from anything -- a web service, a Hadoop cluster, or Twitter -- and build an amazing visualization or predictive tool. You may have done graduate work in a technical field, but you more likely identify as a Data Scientist than whatever's on your diploma. Focus on your strengths -- your ability to pick up any tool in the shed and bend it to your will, your ability to wow with your productivity, and your enthusiasm about data. But be open to other cultures around data -- statisticians, businesspeople, and engineers may bring valuable perspectives and collaborations.""",
            """As a Data Researcher who specializes in Machine Learning or Big Data, you're almost the quintessential Data Scientist! In fact, of all the types of Data Scientist, you're the most likely to embrace the label. Your years of education, likely in Computer Science, give you an unparalleled ability to work creatively with the newest technologies and the biggest data. You can pull insights from data sets from Hadoop to Twitter and back again. Your weakness is probably on the business side, and you should probably develop both domain expertise and the "soft skills" of understanding business problems to maximize your value. But focus on your strengths -- working on the cutting-edge of machine learning and Big Data.""",
            """As a Data Engineer with Machine Learning and Big Data skills, you're at the cutting edge of both technology and the culture around it. More than most other types of Data Scientist, you've embraced Open Source and the Big Data and Data Science buzzwords, and have skills to back it up. You have probably done graduate work, perhaps in an engineering field, and probably have worked with Terabyte-scale data sets. You're probably not a manager, and you're among the least likely type of Data Scientist to be female or to have started a business. To focus on your strengths, keep on the cutting edge of tools for managing enormous data sets. But to broaden your appeal, consider learning more ways of extracting insights, like text analytics or data visualization. """,
        ],
    ]

    return blurbs[row][col]
